/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OtherServicesRouteImport } from './routes/other-services'
import { Route as WeddingGalleryRouteImport } from './routes/wedding-gallery'
import { Route as WeddingRitualsRouteImport } from './routes/wedding-rituals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherServicesRoute = OtherServicesRouteImport.update({
  id: '/other-services',
  path: '/other-services',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingGalleryRoute = WeddingGalleryRouteImport.update({
  id: '/wedding-gallery',
  path: '/wedding-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingRitualsRoute = WeddingRitualsRouteImport.update({
  id: '/wedding-rituals',
  path: '/wedding-rituals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/other-services': typeof OtherServicesRoute
  '/wedding-gallery': typeof WeddingGalleryRoute
  '/wedding-rituals': typeof WeddingRitualsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/other-services': typeof OtherServicesRoute
  '/wedding-gallery': typeof WeddingGalleryRoute
  '/wedding-rituals': typeof WeddingRitualsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/other-services': typeof OtherServicesRoute
  '/wedding-gallery': typeof WeddingGalleryRoute
  '/wedding-rituals': typeof WeddingRitualsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/other-services'
    | '/wedding-gallery'
    | '/wedding-rituals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/other-services'
    | '/wedding-gallery'
    | '/wedding-rituals'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/other-services'
    | '/wedding-gallery'
    | '/wedding-rituals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  OtherServicesRoute: typeof OtherServicesRoute
  WeddingGalleryRoute: typeof WeddingGalleryRoute
  WeddingRitualsRoute: typeof WeddingRitualsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-services': {
      id: '/other-services'
      path: '/other-services'
      fullPath: '/other-services'
      preLoaderRoute: typeof OtherServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-gallery': {
      id: '/wedding-gallery'
      path: '/wedding-gallery'
      fullPath: '/wedding-gallery'
      preLoaderRoute: typeof WeddingGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-rituals': {
      id: '/wedding-rituals'
      path: '/wedding-rituals'
      fullPath: '/wedding-rituals'
      preLoaderRoute: typeof WeddingRitualsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  OtherServicesRoute: OtherServicesRoute,
  WeddingGalleryRoute: WeddingGalleryRoute,
  WeddingRitualsRoute: WeddingRitualsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
